### ISSUE TITLE
Video script

### ISSUE THREAD

**Issue by kx-chen** [MLH-Fellowship/0.5.2-whereami#36]
Create a script for the video.

**Comment by chrisnguyn** [comment]
kai: "okay, so where are you dropping the goods?"

yan: "i'm dropping it at ***1600 Amphitheatre Parkway***"

kai: "wait, where is that? i can't find it on google maps"

yan: "oh okay. it's at ***849VCWC8+W4***"

kai: "what the fu-" 

**PAN OUT AND CUT SCENE**

chris: "relaying your location can be difficult. that's why Google was kind enough to make the Open Location Code system - a geocode system for identifying an area ***anywhere*** on the Earth"

kai: "but ***849VCWC8+W4*** is so hard to remember, what should we do?"

yan: "if only there was a way we could ***translate your location to a word phrase that can be easily remembered***"

chris: "introducing: where am i - a web app, command line tool, AND discord bot that can easily relay your location using a few words. use it today!"

**Comment by kx-chen** [comment]
kai: "okay, so where are you dropping the goods?"

chris: "i'm dropping it at 49 degrees north one hundred and twenty three min..."

yan: "wait, what are you guys doing?!"

kai: "uhhh nothing..."

yan: "don't share your location with coordinates, use where am i - a web app, command line tool, AND discord bot that can easily relay your location using a few words. "

chris: "oh, cool, how does it work?

(voiceover and screen recording of app)
yan: "just enter the location here, and share the location phrase!" 

chris: "oh cool. so, kai, i'm dropping the goods at white.train.open.simple.letter" 

(screen recording of kai typing in the word phrase and map zooming to the location)
kai: "oh, cool, got it!"

**Comment by chrisnguyn** [comment]
kai: "okay, so where are you dropping the goods?"

chris: "i'm dropping it at ***1600 Amphitheatre Parkway***"

kai: "wait, where is that? i can't find it on google maps"

chris: "oh okay. it's at ***849VCWC8+W4***"

kai: "what the fu-" 

**PAN OUT AND CUT SCENE**

yanny: "relaying your location can be difficult. that's why Google was kind enough to make the Open Location Code system - a geocode system for identifying an area ***anywhere*** on the Earth"

kai: "but ***849VCWC8+W4*** is so hard to remember, what should we do?"

chris: "if only there was a way we could ***translate your location to a word phrase that can be easily remembered***"

yanny: "introducing: where am i - a web app, command line tool, AND discord bot that can easily relay your location using a few words. use it today!"
